version: '3.8'

services:
  nats:
    image: nats:2.9.21-alpine
    ports:
      - "4223:4222"
      - "8223:8222"
    networks:
      - microservices-net

  microservice1:
    build:
      context: ./bookin-microservice
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - microservices-net
    restart: always
    command: npm run start:prod

  microservice2:
    build:
      context: ./Liquor
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    networks:
      - microservices-net
    restart: always
    command: npm run start:prod

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - microservice1
      - microservice2
    networks:
      - microservices-net
    restart: always
    command: npm run start:prod

networks:
  microservices-net:
    driver: bridge